// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2019-04-18T13:57:00.423Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://fwimeyiwm8.execute-api.eu-west-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'eu-west-1'
        }
    ],
    aws_cognito_region: 'eu-west-1',
    aws_project_region: 'eu-west-1',
    aws_user_pools_id: 'eu-west-1_txNxeYZ2q',
    aws_user_pools_web_client_id: '2agf3u3fsmgbgsleqrjfgujcs8'
};

export default awsmobile;
